### ISSUE TITLE
udpate nuget package with automapper 6.0.0

### ISSUE THREAD

**Issue by MienDev** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#15]
Great jbogard,  please be kind to update the nuget package that work with automapper 6.0.0

`
Build started, please wait...
C:\Program Files\dotnet\sdk\1.0.1\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: 
Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
 [F:\S2\xxx.cms\src\xxx.cms\xxx.cms.csproj]
Startup.cs(30,13): error CS1705: Assembly 'AutoMapper.Extensions.Microsoft.DependencyInjection' with identity 'AutoMapper.Extensions.Microsoft.DependencyInjection, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' uses 'AutoMapper, Version=5.0.2.0, Culture=neutral, PublicKeyT
oken=be96cd2c38ef1005' which has a higher version than referenced assembly 'AutoMapper' with identity 'AutoMapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' [F:\S2\xxx.cms\src\xxx.cms\xxx.cms.csproj]
C:\Program Files\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'F:\S2\xxx.cms\src\xxx.cms\xxx.cms.csproj'. This can indicate a missing project reference. [F:\S2\xxx.cms\test\xxx.Cms.IntgratedTests\xxx.Cms.
IntgratedTests.csproj]
`

**Comment by jbogard** [comment]
Done!
